### ISSUE TITLE
unhandled FileLog error causing crash

### ISSUE THREAD

**Issue by gbirchmeier** [connamara/quickfixn#209]
Reported on list.
http://lists.quickfixn.com/pipermail/quickfixn-quickfixn.com/2013q2/000866.html

Not sure how widespread.  Only reported by this single user.

May end up being resolved by #205 and/or #197 which are in active development.

```
Application: LiveTrader.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
Stack:
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.WriteCore(Byte[], Int32, Int32)
   at System.IO.FileStream.FlushInternalBuffer()
   at System.IO.FileStream.Flush(Boolean)
   at System.IO.FileStream.Flush()
   at System.IO.StreamWriter.Flush(Boolean, Boolean)
   at System.IO.StreamWriter.Write(Char[], Int32, Int32)
   at System.IO.TextWriter.WriteLine(System.String)
   at QuickFix.FileLog.OnOutgoing(System.String)
   at QuickFix.Session.Send(System.String)
   at QuickFix.Session.SendRaw(QuickFix.Message, Int32)
   at QuickFix.Session.GenerateLogon()
   at QuickFix.Session.Next()
   at QuickFix.Transport.SocketInitiator.SocketInitiatorThreadStart(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
```

**Comment by gbirchmeier** [comment]
addressed by #505
