### ISSUE TITLE
Application crash due to unhandled exception

### ISSUE THREAD

**Issue by amlodkowski** [connamara/quickfixn#293]
Issue happens on a fix initiator when acceptor is not accepting connections due to trading lapse

Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
Stack:
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean)
   at System.IO.StreamReader..ctor(System.String, System.Text.Encoding, Boolean, Int32, Boolean)
   at System.IO.StreamReader..ctor(System.String, System.Text.Encoding, Boolean, Int32)
   at System.IO.StreamReader..ctor(System.String, Boolean)
   at QuickFix.FileStore.ConstructFromFileCache()
   at QuickFix.FileStore.open()
   at QuickFix.FileStore.Reset()
   at QuickFix.SessionState.Reset(System.String)
   at QuickFix.Session.SendRaw(QuickFix.Message, Int32)
   at QuickFix.Session.GenerateLogon()
   at QuickFix.Session.Next()
   at QuickFix.Transport.SocketInitiator.SocketInitiatorThreadStart(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)

**Comment by brobits** [comment]
> Issue happens on a fix initiator when acceptor is not accepting connections due to trading lapse

Are you still experiencing this exception?  We may be interested in resolving this issue.  We would need more information on the execution environment and configuration.

Please re-open this issue with the QuickFIX/n configuration you're using, the timestamps of when your counterparty is/not accepting peer connections, and any logs you may be able to provide to debug this issue.
