### ISSUE TITLE
Hello, I have an exception in client if my server is shuting down

### ISSUE THREAD

**Issue by nmwebeyez** [connamara/quickfixn#457]
Those are exception details
Exception: System.NullReferenceException

Message: Object reference not set to an instance of an object.

StackTrace:    at QuickFix.AbstractInitiator.Connect() in D:\DownLoads\quickfixn-master\QuickFIXn\AbstractInitiator.cs:line 304
   at QuickFix.Transport.SocketInitiator.OnStart() in D:\DownLoads\quickfixn-master\QuickFIXn\Transport\SocketInitiator.cs:line 187
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

The function that exception is thrown from 
```
protected void Connect()
        {
            lock (sync_)
            {
                HashSet<SessionID> disconnectedSessions = new HashSet<SessionID>(disconnected_);
                foreach (SessionID sessionID in disconnectedSessions)
                {
                    Session session = Session.LookupSession(sessionID);
                    if (session.IsEnabled)
                    {
                        if (session.IsNewSession)
                            session.Reset("New session");
                        if (session.IsSessionTime)
                            DoConnect(sessionID, _settings.Get(sessionID));
                    }
                }
            }
        }
```

Can you please change condition `if (session.IsEnabled) `to `if (session!=null && session.IsEnabled)`

**Comment by gbirchmeier** [comment]
Looks like a legit bug (that we'll look into fixing), but I suspect it's only happening because your config file is wrong.  Can I see your config?  (Are you 100% sure that `session` is null?)

**Comment by gbirchmeier** [comment]
Submitter never followed up.  Without further corroboration, not going to spend time on it.
