### ISSUE TITLE
HttpServer Issue with SessionID

### ISSUE THREAD

**Issue by blindvit** [connamara/quickfixn#786]
I found one case when session cgf file has SenderSubID but the session listed in admin interface does not include it. This results into "Session not found" exception when user clicks the session details link. This exception is crashing the main process.

- Add ability to attach SenderSubID to the session details link
- For not found sessionId just render "Session not found message" to the html output (https://github.com/connamara/quickfixn/blob/ce2cdf6ddd966329874be9e6c8a6006c1214c28d/QuickFIXn/HttpServer.cs#L285)

```
The service threw an unhandled exception, System.Exception: Session not found
   at Acceptor.HttpServer.SessionDetails(HttpListenerRequest request)
   at Acceptor.HttpServer.ConnectionThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by gbirchmeier** [comment]
Yep, I see what's up.  The HttpServer constructs SessionID strings in a pretty naive way.  I bet I can do that better.

**Comment by gbirchmeier** [comment]
I started rewriting the whole HttpServer.  Hopefully done tomorrow.
