### ISSUE TITLE
ConfigError (Non:Session->Log) after updating QuickFix version

### ISSUE THREAD

**Issue by RomainAn** [connamara/quickfixn#900]
Hello everyone.

Recently we updated our QuickFix version from 1.11.2 to 1.12.0.

And now we do see this exception :

Unhandled exception. QuickFix.ConfigError: Configuration failed: Session 'Non:Session->Log' not found

Am I missing out something ?

Best regards.

**Comment by gbirchmeier** [comment]
Can you post the full stacktrace?

And also your config?  (You can edit out anything sensitive)

**Comment by RomainAn** [comment]
Hello ! Thank you for your answer :

```
<event> Session FIX.4.2:XXXXXX->XXXXXXX disconnecting: Resetting...
Unhandled exception. QuickFix.ConfigError: Configuration failed: Session 'Non:Session->Log' not found
   at QuickFix.SessionSettings.Get(SessionID sessionId)
   at QuickFix.Logger.FileLogFactory.Create(SessionID sessionId)
   at QuickFix.Logger.CompositeLogFactory.<>c.<CreateNonSessionLog>b__3_0(ILogFactory f)
   at System.Linq.Enumerable.ArraySelectIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.ArraySelectIterator`2.ToArray()
   at QuickFix.Logger.CompositeLogFactory.CreateNonSessionLog()
   at QuickFix.Logger.NonSessionLog.OnEvent(String s)
   at QuickFix.Transport.SocketInitiator.OnStart()
```

```
{
  "ConnectionType": "initiator",
  "FileLogPath": "/log",
  "FileStorePath": "/fix",
  "HeartBtInt": "30",
  "TimestampPrecision": "Milliseconds",
  "PersistMessages": "N",
  "ReconnectInterval": "10",
  "ResetOnLogon": "N",
  "ScreenLogShowEvents": "Y",
  "ScreenLogShowIncoming": "Y",
  "ScreenLogShowOutgoing": "Y",
  "SocketNodelay": "Y",
  "UseDataDictionary": "N",
  "Sessions": [
    {
      "Name": "XXXXXXX",
      "BeginString": "FIX.4.2",
      "TargetCompID": "XXXXXX",
      "SenderCompID": "XXXXXXX",
      "SocketConnectHost": "XX.XX.XXX.XX",
      "SocketConnectPort": "XXXX",
      "StartTime": "23:00:00",
      "EndTime": "01:20:15",
      "TimeZone": "Eastern Standard Time",
    }
  ]
}

```

Thank you again for your time and kind help !

**Comment by gbirchmeier** [comment]
Ah, it's the CompositeLogFactory.

Can you tell me what LogFactories you are passing in to CompositeLogFactory?  Looks like FileLogFactory for one.

(I think I got this, but want to cover all my bases)

**Comment by gbirchmeier** [comment]
Never mind, I've got it
